version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: "gradle"
    directory: "/projects"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "com.google.devtools.ksp*"
      kotest:
        patterns:
          - "io.kotest*"

  - package-ecosystem: "gradle"
    directory: "/examples"
    schedule:
      interval: "weekly"
      day: "monday"
