apply(plugin = "maven-publish")

// Dokka Javadoc does not support KMP projects. Maven Central accepts an empty Javadoc JAR
// for Kotlin Multiplatform libraries; HTML API docs are generated by dokkaGenerateHtml.
val dokkaJavadocJar by tasks.registering(Jar::class) {
    archiveClassifier.set("javadoc")
}

configure<PublishingExtension> {
    publications.withType<MavenPublication> {
        artifact(dokkaJavadocJar)
        pom {
            name.set("Kofixture")
            description.set("Kotlin Multiplatform test fixture generation library")
            url.set("https://github.com/kofixture/kofixture")

            licenses {
                license {
                    name.set("The Apache Software License, Version 2.0")
                    url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                }
            }

            scm {
                connection.set("scm:git:https://github.com/kofixture/kofixture.git")
                developerConnection.set("scm:git:ssh://git@github.com/kofixture/kofixture.git")
                url.set("https://github.com/kofixture/kofixture")
            }

            developers {
                developer {
                    name.set("Kofixture Contributors")
                    id.set("arkadiusz")
                    name.set("Arkadiusz Szast")
                    email.set("szast.arkadiusz@pm.me")
                    organization.set("Kofixture")
                    organizationUrl.set("https://github.com/kofixture")
                }
            }
        }
    }
}

apply(from = rootProject.file("gradle/signing.gradle.kts"))
