name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/prepare-env

      - name: Check formatting
        working-directory: projects
        run: ./gradlew spotlessCheck

      - name: Static analysis
        working-directory: projects
        run: ./gradlew detekt

      - name: Build and test
        working-directory: projects
        run: ./gradlew build jvmTest

      - name: API compatibility check
        working-directory: projects
        run: ./gradlew apiCheck

  publish:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/prepare-env

      - name: Publish to Maven Central
        working-directory: projects
        run: IS_RELEASE=true ./gradlew publishAggregationToCentralPortal
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
